### ISSUE TITLE
Wrong calculations for Israel?

### ISSUE THREAD

**Issue by ittayd** [statsccpr/ind-cov-mort#1]
Israel's population is ~9.2M (https://en.wikipedia.org/wiki/Demographics_of_Israel)

The ISCDR looks low (ranked #212) given the recent rise in deaths and also that Israel has a young population (median 30 years).

**Comment by heuveline** [comment]
The population numbers are from the UN. Not sure where the difference with Wikipedia numbers come from.
The number of deaths are from JHU.
Indeed the young age structure causes the indirectly standardized rate (.64) to be 1/3 higher than the crude rate (.48)
